version: 2
jobs:
  build:
    machine:
      enabled: true

steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
          sudo apt-get update
          sudo apt-get -y install wget zip unzip

- run:
    name: Download Godot 3.2.1
    command: |
        wget -q https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        unzip Godot_v3.2.1-stable_linux_headless.64.zip
        mv Godot_v3.2-stable_linux_headless.64 godot
        chmod +x godot

- run:
    name: Download Godot 3.2.1 Export Templates
    command: |
        wget -q https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/templates
        unzip Godot_v3.2.1-stable_export_templates.tpz -d ~/.local/share/godot/templates
        mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.1.stable

- run:
    name: Export wasm build
    command: |
        mkdir -p wasm
        ./godot --export wasm project.godot "wasm/idk.html"
        cd wasm\
        git init
        git add .
        git commit "test"
        git remote add origin git@github.com:aleksandrabanasiak/idk.git
        git push -u origin master