version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip
      - run:
          name: Download Butler
          command: |
              wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
              unzip butler.zip
              chmod +x butler
      - run:
          name: Download Godot 3.2.1
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
              unzip Godot_v3.2.1-stable_linux_headless.64.zip
              mv Godot_v3.2.1-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.2.1 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.2.1-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.1.stable
      - run:
          name: Export Win64 build
          command: |
              mkdir -p win64
              ./godot --export win64 project.godot "win64/Final_Destination.exe"
      - run:
          name: Upload win64 build
          command: ./butler push win64 squiggly-fox/final-destination:win-64bit
      - run:
          name: Export Linux build
          command: |
              mkdir -p linux
              ./godot --export linux project.godot "linux/Final_Destination"
      - run:
          name: Upload Linux build
          command: ./butler push linux squiggly-fox/final-destination:linux
      - run:
          name: Export Mac OS build
          command: |
              ./godot --export mac project.godot "Final_Destination"
              mv Final_Destination Final_Destination.zip
      - run:
          name: Upload Mac OS build
          command: ./butler push Final_Destination.zip squiggly-fox/final-destination:macos

